### PR TITLE
Rework visibility text

### LINKED ISSUE #824: Update Visibility help text
### Descriptive summary

The recent revision to help text in CC visibly exposed the fact that the help text for the Visibility field is quite long. Not only is it cluttering the page, help text that long generally isn't very helpful for users. I talked with @heidisb and she came up with the following help text.

I also think the layout for the Embargo and Lease options could be cleaned up and will add that to the PR.

### Heidi's suggested update to the help text

> Who should be able to view or download this content and see the associated metadata? 
>  
> This is a blanket visibility setting. If you want to be able to selectively allow access, choose Private. 

### Heidi's suggested update to the labels

> **Open Access** - Everyone. Keep in mind this **may** be viewed as publishing and impact your ability to patent your work and/or publish your work in a journal. Check out [SHERPA/RoMEO](http://www.sherpa.ac.uk/romeo/) for specific publishers' copyright policies. 
> 
> **Your Institution** - Only users who are logged in through your institution
> 
> **Private** - Only users and/or groups that have been given specific access in the "Share With" section.

### How it currently looks

screen shot 2016-05-27 at 11 20 53 am

### PR DESCRIPTION
**Pull request by escowles**
Fixes #824 

* Avoid wall of text and inline labels that were displaying poorly.
* Use the same labels for both works and collections, configured in a locale file instead of inline in the views.

@projecthydra/sufia-code-reviewers

### CODE REVIEW

**Comment by awead** [comment]
@escowles see https://github.com/cbeer/fcrepo_wrapper/pull/21

**Comment by awead** [comment]
@escowles now it's blocked by this https://github.com/projecthydra/curation_concerns/pull/869

**Comment by mjgiarlo** [comment]
Looks good to me.

Heads-up to @mtribone @projecthydra/sufia-ui-ux-advisors that this change will be coming to Sufia soon. Thoughts before we merge this?

**Comment by justcolin** [comment]
Looks good to me. Thanks @escowles!

**Pull request merged**
