### PR TITLE
Changing version revision to use the correct signature for CharacterizeJob

### PR DESCRIPTION
**Pull request by cam156**
Fixes https://github.com/projecthydra/sufia/issues/2404

The signature for characterization job changed a while back and this update was missed becuase the test is completely mocked.

I changed the mocking to the correct signature, but I am not certain that the test is really testing all that we want it to test.  Do people have ideas on how to better test the integration without writing an integration test?

@projecthydra/sufia-code-reviewers

### CODE REVIEW

**Comment by awead** [comment]
I suspect it didn't blow up because "working_path" in the old signature and "file_set.id" in the new sig. were just strings, so the test didn't see a difference. I'm not sure if there really is a way around this other than to have an integration test.

But, something doesn't look right about that second parameter. You're passing `file_set.id` except that's supposed to be an "identifier for a Hydra::PCDM::File" according to the documentation. In the other classes that are invoked by CharacterizeJob, it's also expecting an identifier for a Hydra::PCDM::File:

https://github.com/projecthydra/curation_concerns/blob/master/app/services/curation_concerns/working_directory.rb#L7

https://github.com/projecthydra/curation_concerns/blob/master/app/jobs/create_derivatives_job.rb#L6

**Comment by cam156** [comment]
@awead good catch!

**Comment by awead** [comment]
@cam156 LGTM. I still don't have a good answer for the test coverage question, though. I'm good with merging if this solves the current problem, even if it doesn't protect us from it happening again in the future.

**Comment by cam156** [comment]
@awead it does fix the revision reversion issue in Sufia (I tested that locally), so merging it seems like a good idea.

**Pull request merged**
