### PR TITLE
Return the first title for the page_title

### PR DESCRIPTION
**Pull request by mjgiarlo**
Fixes projecthydra/sufia#2052

@projecthydra/sufia-code-reviewers

Happy to have suggestions for testing strategies. Didn't see much coverage of this in the codebase already but perhaps I missed something obvious.

### CODE REVIEW

**Comment by jcoyne** [comment]
Add a test in spec/presenters/curation_concerns/work_show_presenter_spec.rb, test for "foo" when solr_document.title returns ['foo', 'bar']

**Comment by atz** [comment]
Definitely worth a test to codify expectation.

**Comment by mjgiarlo** [comment]
:+1:

**Comment by jeremyf** [comment]
Should we use `Array.wrap(solr_document.title).first`? I don't know how deep the assumption of what `#title` would look like.

**Comment by awead** [comment]
Given its current position, `title` is pretty ubiquitous as an array, defined in `CurationConcerns::RequiredMetadata`. If it's truly "required" and is defined as multivalued, then I think we should always assume it's an array and not try to coax it into one because if it's somehow not an array, we've done something wrong and it should fail.

**Comment by mjgiarlo** [comment]
Thx, all. Pushing my changes soon.

**Comment by mjgiarlo** [comment]
@jeremyf Yeah, `#title` is already `Array.wrap`ped here: https://github.com/projecthydra/curation_concerns/blob/master/app/models/concerns/curation_concerns/solr_document_behavior.rb#L67

**Comment by mjgiarlo** [comment]
@jcoyne @jeremyf @awead I believe this is ready.

**Pull request merged**
