### PR TITLE
Add selector for representative media to file manager members, fix #958

### LINKED ISSUE #958: Add 'representative file' selection to the file manager alongside thumbnail selection
Changing the thumbnail affects list views but does not affect the work show view. This is because the work show view uses representative file to determine what to display. It feels like a bug to change the thumbnail and then not see that reflected when you return to the parent work. Adding representative file selection into the file manager would help mitigate this confusion.

The distinction will probably still be confusing when the collection is entirely images, but I'm not sure there's anything we can do about that!

### PR DESCRIPTION
**Pull request by hackmastera**
@tpendragon this just echoes what you did in https://github.com/projecthydra/curation_concerns/pull/926. Would you like me to also add in the indexing piece?

### CODE REVIEW

**Comment by hackmastera** [comment]
Okay @jpstroop advised me to go ahead with the indexing but now I'm confused -- why did you add thumnail_id_ssim when there is already hasRelatedImage_ssim. Here's an example from my index:

See thumbnail predicate defined https://github.com/projecthydra/curation_concerns/blob/master/app/models/concerns/curation_concerns/has_representative.rb

```
      {
        "system_create_dtsi":"2016-08-29T15:21:57Z",
        "system_modified_dtsi":"2016-09-02T19:25:33Z",
        "has_model_ssim":["GenericWork"],
        "id":"st74cq794",
        "accessControl_ssim":["a8f1d3dd-a0a0-43c5-a484-d004d025fc6e"],
        "hasRelatedMediaFragment_ssim":["pr76f369j"],
        "hasRelatedImage_ssim":["sb397864f"],
        "depositor_ssim":["a@chemheritage.org"],
        "depositor_tesim":["a@chemheritage.org"],
        "title_tesim":["Parent work"],
        "date_uploaded_dtsi":"2016-08-29T15:21:57Z",
        "date_modified_dtsi":"2016-09-02T19:25:33Z",
        "thumbnail_path_ss":"/assets/default-c6018ff301250c55bcc663293e1816c7daece4159cbc93fc03d9b35dbc3db30d.png",
        "thumbnail_id_ssim":["sb397864f"],
        "member_ids_ssim":["sb397864f",
          "bc386j55f",
          "pr76f369j",
          "3484zh205",
          "m326m2125"],
        "suppressed_bsi":false,
        "human_readable_type_tesim":["Generic Work"],
        "edit_access_person_ssim":["a@chemheritage.org"],
        "_version_":1544389220265623552,
        "timestamp":"2016-09-02T19:25:33.901Z",
        "score":1.0},
```

**Comment by jcoyne** [comment]
@hackmastera I suspect that extra thumbnail_id field may just be an oversight (probably by me)

**Comment by hackmastera** [comment]
@jcoyne it does seem sort of strange to index them by their predicate names rather than their property names

**Comment by hackmastera** [comment]
@jcoyne I think I can clean the indexing up a little. Do y'all prefer the solr fields to be called hasRelatedImage and hasRelatedMediaFragment, as they were/are currently, or thumbnail_id and representative_id, after their property names in the models?

**Comment by hackmastera** [comment]
i cleaned up the thumbnail_id solr field and set up representative_id indexing in https://github.com/projecthydra/curation_concerns/pull/962

**Pull request merged**
