### PR TITLE
Backport #1169 to 1.7.x

### PR DESCRIPTION
**Pull request by dunn**
See #1169.

@projecthydra/sufia-code-reviewers

### CODE REVIEW

**Comment by dunn** [comment]
https://travis-ci.org/projecthydra/curation_concerns/jobs/214691428#L1779 looks like the same flaky spec as in https://github.com/projecthydra/curation_concerns/pull/1169#issuecomment-288559236

**Comment by mjgiarlo** [comment]
@dunn Restarted. Sorry!

**Comment by dunn** [comment]
¯\\(´o｀)/¯

**Comment by dunn** [comment]
Third time was the charm!

**Comment by mjgiarlo** [comment]
@dunn :tada:

**Pull request merged**
