### PR TITLE
Improved content negotiation

### PR DESCRIPTION
**Pull request by jcoyne**
@projecthydra/sufia-code-reviewers

Encode suburis as hashcodes. Encode subject URIs separately (previously they would go to the controller for the main model).

### CODE REVIEW

**Comment by tpendragon** [comment]
If you encode contained resources as hash-URIs, what happens to actual hash-uris of those contained resources? #list_source#1? I don't see any code to actually pull in those nodes, so is there a different strategy I'm missing?

**Comment by jcoyne** [comment]
@tpendragon Good point. I haven't handled those yet.  Mostly this provides a framework for that work to occur.

**Comment by jcoyne** [comment]
@tpendragon I fixed the hash code issue.

**Comment by tpendragon** [comment]
Test failed.

**Comment by jcoyne** [comment]
@tpendragon it's 💚 now.

**Pull request merged**
