### PR TITLE
Use standard bootstrap components for the admin dashboard

### PR DESCRIPTION
**Pull request by cbeer**
Before:

screen shot 2016-10-24 at 12 44 39 pm

After:

screen shot 2016-10-24 at 12 49 12 pm

### CODE REVIEW

**Comment by mjgiarlo** [comment]
Comments on these changes, @jcoyne @tpendragon @elrayle @cam156 @scherztc @ggeisler?

**Comment by ggeisler** [comment]
👍  This will make theming/institutional customization much easier. Thanks @cbeer.

**Comment by jcoyne** [comment]
:+1:

**Comment by tpendragon** [comment]
:+1:

**Pull request merged**
